apiVersion: osac.openshift.io/v1alpha1
kind: HostLease
metadata:
  name: hostlease-1
  namespace: danniesh
spec:
  externalHostID: 758ddf40-69a9-460b-86b2-2ea876d33d5b
  externalHostName: MOC-R4PAC08U33-S1A
  hostType: fc830
  hostClass: openstack
  networkClass: openstack
  networkInterfaces:
    - macAddress: aa:bb:cc:dd:ee:f1
      network: private-vlan-network
  # poweredOn: on
  templateID: osac.templates.bm_host_image_provision
